name: Terraform Dev Only

on:
  push:
    paths:
      - 'infra/**'
      
jobs:
  terraform-init:
    name: Terraform init & Plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan ##-var-file="dev.tfvars"

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./infra/tfplan

  # terraform-apply:
  #   name: Terraform Apply
  #   runs-on: ubuntu-latest
  #   needs: terraform-init
  #   environment:
  #     name: approval-apply

  #   env:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     AWS_REGION: us-east-1

  #   defaults:
  #     run:
  #       working-directory: ./infra

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4

  #     - name: Set up Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: 1.12.0

  #     - name: Terraform Init
  #       run: terraform init

  #     - name: Download tfplan
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: tfplan
  #         path: ./infra

  #     - name: Terraform Apply
  #       run: terraform apply -auto-approve 


